# Generated by Django 3.2.3 on 2021-05-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisionVision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision', models.CharField(max_length=200)),
                ('vision', models.CharField(max_length=200)),
                ('imagen_vision', models.ImageField(null=True, upload_to='Vision')),
                ('imagen_mision', models.ImageField(null=True, upload_to='Mision')),
            ],
        ),
    ]
