# Generated by Django 3.2.3 on 2021-06-07 01:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_misionvision'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='serv_titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servicio', verbose_name='Ingrese servicio a realizar:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boletafactura',
            name='bol_fac_fecha_emision',
            field=models.DateField(verbose_name='Ingrese la Fecha de emision de la Boleta o Factura:'),
        ),
        migrations.AlterField(
            model_name='boletafactura',
            name='bol_fac_total',
            field=models.BigIntegerField(verbose_name='Ingrese el valor total de la Boleta o Factura:'),
        ),
        migrations.AlterField(
            model_name='boletafactura',
            name='desc_bol_fac',
            field=models.CharField(choices=[['Boleta', 'Boleta'], ['Factura', 'Factura']], max_length=7, verbose_name='Ingrese una breve descipción '),
        ),
        migrations.AlterField(
            model_name='producto',
            name='desc_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipomarca', verbose_name='Seleccione la Marca asociada al producto:'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Producto:'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_stock',
            field=models.BigIntegerField(verbose_name='Cantidad a ingresar:'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prov_nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor', verbose_name='Seleccione el Proveedor del producto:'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='prov_nombre',
            field=models.CharField(max_length=100, verbose_name='Ingrese el Nombre del Proveedor:'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='prov_rut_empresa',
            field=models.CharField(max_length=12, verbose_name='Ingrese el Rut de la Empresa asociada:'),
        ),
        migrations.AlterField(
            model_name='recepcionpedido',
            name='desc_recepcion',
            field=models.CharField(max_length=150, verbose_name='Ingrese el nombre y cantidad de Productos recibidos:'),
        ),
        migrations.AlterField(
            model_name='recepcionpedido',
            name='fecha_recepcion',
            field=models.DateField(verbose_name='Seleccione la Fecha de recepción del pedido:'),
        ),
        migrations.AlterField(
            model_name='recepcionpedidoproducto',
            name='costo_recepcion',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Ingrese el costro de recepción. Si no hay costo agregado dejar en blanco.'),
        ),
        migrations.AlterField(
            model_name='recepcionpedidoproducto',
            name='fecha_recepcion',
            field=models.DateField(verbose_name='Seleccione la Fecha de rececepción'),
        ),
        migrations.AlterField(
            model_name='recepcionpedidoproducto',
            name='prod_cantidad',
            field=models.BigIntegerField(verbose_name='Ingrese Cantidad entrante del Producto:'),
        ),
        migrations.AlterField(
            model_name='recepcionpedidoproducto',
            name='prod_nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto', verbose_name='Ingrese el nombre del Producto entrante'),
        ),
        migrations.AlterField(
            model_name='region',
            name='desc_region',
            field=models.CharField(max_length=100, verbose_name='Ingrese el nombre de la región a ingresar'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cli_rut',
            field=models.CharField(max_length=8, verbose_name="Ingrese su RUT sin punto y sin DV, Ej: '20537529' "),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='res_desc_reserva',
            field=models.CharField(max_length=200, verbose_name='Agregue una breve descripción del vehiculo y/o sus errores:'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='res_fecha_pedido_reserva',
            field=models.DateField(verbose_name='Seleccione dia a reservar:'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='res_hora_reservada',
            field=models.DateField(choices=[['08:00', '08:00'], ['09:00', '09:00'], ['10:00', '10:00'], ['11:00', '11:00'], ['12:00', '12:00'], ['13:00', '13:00'], ['14:00', '14:00'], ['15:00', '15:00'], ['16:00', '16:00'], ['17:00', '17:00'], ['18:00', '18:00'], ['19:00', '19:00'], ['20:00', '20:00']], max_length=5, verbose_name='Seleccione hora a reservar:'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='serv_costo',
            field=models.BigIntegerField(verbose_name='Ingrese el costo del Servicio a realizar:'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='serv_descripcion',
            field=models.CharField(max_length=45, verbose_name='Ingrese una breve descripción del servicio:'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='serv_titulo',
            field=models.CharField(max_length=35, verbose_name='Ingrese el Titulo/Nombre del Servicio:'),
        ),
        migrations.AlterField(
            model_name='tipoempleado',
            name='desc_tipo_empleado',
            field=models.CharField(max_length=100, verbose_name='Ingrese el nombre del nuevo Tipo Empleado:'),
        ),
        migrations.AlterField(
            model_name='tipomarca',
            name='desc_marca',
            field=models.CharField(max_length=50, verbose_name='Ingrese el nombre de la nueva marca asociada:'),
        ),
        migrations.AlterField(
            model_name='tipopago',
            name='desc_medio_pago',
            field=models.CharField(max_length=50, verbose_name='Ingrese el nuevo medio de pago a integrar:'),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='user_desc',
            field=models.CharField(max_length=30, verbose_name='Ingrese el nuevo Tipo Usuario el cual sera parte del sistema:'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_contrasena',
            field=models.CharField(max_length=20, verbose_name='Ingrese la contraseña del nuevo usuario:'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_desc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipousuario', verbose_name='Integre una breve descripcion de cargos del nuevo usuario:'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_nombre',
            field=models.CharField(max_length=20, verbose_name='Ingrese el Nombre/Tag del nuevo Usuario:'),
        ),
    ]
