# Generated by Django 3.2.3 on 2021-06-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210606_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='res_hora_reservada',
            field=models.CharField(choices=[['08:00', '08:00'], ['09:00', '09:00'], ['10:00', '10:00'], ['11:00', '11:00'], ['12:00', '12:00'], ['13:00', '13:00'], ['14:00', '14:00'], ['15:00', '15:00'], ['16:00', '16:00'], ['17:00', '17:00'], ['18:00', '18:00'], ['19:00', '19:00'], ['20:00', '20:00']], max_length=5, verbose_name='Seleccione hora a reservar:'),
        ),
    ]
