# Generated by Django 3.2.3 on 2021-06-08 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210607_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletafactura',
            name='desc_medio_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipopago'),
        ),
        migrations.AlterField(
            model_name='detalleservicio',
            name='desc_medio_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pagoservicio'),
        ),
        migrations.AlterField(
            model_name='pagoservicio',
            name='desc_medio_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipopago'),
        ),
        migrations.AlterField(
            model_name='tipopago',
            name='desc_medio_pago',
            field=models.CharField(max_length=50, verbose_name='Ingrese el nuevo medio de pago a integrar:'),
        ),
    ]
