# Generated by Django 3.2.3 on 2021-06-08 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210607_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleservicio',
            name='desc_medio_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipopago'),
        ),
    ]
